name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Skip this workflow if the commit message contains [skip ci] or is from the GitHub Actions bot
jobs:
  check_skip:
    runs-on: ubuntu-latest
    # Skip if this is a tag push
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - id: skip_check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMITTER=$(git log -1 --pretty=%cn)
          if [[ "$COMMIT_MSG" == *"[skip ci]"* || "$COMMITTER" == "github-actions"* ]]; then
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.should_skip != 'true' && !startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/build-test.yml
    with:
      lint: true
